# Generated by Django 5.2.8 on 2025-11-20 07:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdress',
            new_name='UserAddress',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='signer_moblie',
            new_name='signer_mobile',
        ),
    ]
