# Generated by Django 5.2.8 on 2025-11-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支付单', 'verbose_name_plural': '支付清单'},
        ),
    ]
