# Generated by Django 5.2.8 on 2025-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT', '支付'), ('REFUND', '退款')], default='PAYMENT', max_length=20, verbose_name='交易类型'),
        ),
    ]
