# Generated by Django 5.2.8 on 2025-11-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': '店铺详情', 'verbose_name_plural': '店铺详情'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': '商家钱包', 'verbose_name_plural': '商家钱包'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'verbose_name': '商家流水', 'verbose_name_plural': '商家流水'},
        ),
    ]
