# Generated by Django 5.2.8 on 2025-11-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': '购物单', 'verbose_name_plural': '购物车'},
        ),
    ]
