# Generated by Django 5.2.8 on 2025-11-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_category_options_alter_productsku_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeckillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('seckill_stock', models.PositiveIntegerField(default=0, verbose_name='秒杀库存')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='秒杀商品')),
            ],
        ),
    ]
