# Generated by Django 5.2.8 on 2025-11-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单列表'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单项', 'verbose_name_plural': '订单项列表'},
        ),
    ]
