# Generated by Django 5.2.8 on 2025-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_parent_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_buyer',
            field=models.BooleanField(default=False, verbose_name='买家已删除'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_seller',
            field=models.BooleanField(default=False, verbose_name='卖家已删除'),
        ),
    ]
