# Generated by Django 5.2.8 on 2025-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_deleted_by_buyer_order_is_deleted_by_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('SHIPPED', '已发货'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('REFUNDED', '已退款')], default='PENDING', max_length=20),
        ),
    ]
