# Generated by Django 5.2.8 on 2025-11-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '商品种类', 'verbose_name_plural': '商品种类'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='productspu',
            options={'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
    ]
